name: Release new version to s3
on:
  release:
    types: [created]
jobs:
  release-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npm install -g @oclif/dev-cli
      - run: npm install -g aws-sdk
      - run: oclif-dev pack --targets=linux-x64,linux-arm,darwin-x64,darwin-arm64
      - run: oclif-dev publish --targets=linux-x64,linux-arm,darwin-x64,darwin-arm64
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
